repository:
  private: true
  has_issues: false
  has_wiki: false
  has_projects: false
  has_downloads: true
  default_branch: master
  allow_squash_merge: false
  allow_merge_commit: true
  allow_rebase_merge: false
teams: []
branches: []
